version: '3.8'
networks:
  pnet:
    driver: bridge
volumes:
  gems:
  pg-data:
  node-modules:
services:
  db:
    image: postgres
    networks:
      - pnet
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  webpack:
    build: .
    command: bundle exec bin/webpack-dev-server
    networks:
      - pnet
    volumes:
      - ./:/usr/src/app
      - gems:/usr/local/bundle
      - node-modules:/usr/src/app/node_modules
    ports:
      - 3035:3035
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - pnet
    volumes:
      - ./:/usr/src/app
      - gems:/usr/local/bundle
      - node-modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
      - webpack
      - chrome
    environment:
      PG_PASSWORD: password
      HUB_URL: http://chrome:4444/wd/hub
      WEBPACKER_DEV_SERVER_HOST: webpack

  chrome:
    image: selenium/standalone-chrome-debug
    networks:
      - pnet
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
